version: '3.8'

services:
  server-a:
    build:
      context: .
      dockerfile: Dockerfile
    image: opentelemetry-server-a:latest
    ports:
      - "8080:8080"
    environment:
      - SERVICE_NAME=server-a
      - OTEL_EXPORTER_ZIPKIN_ENDPOINT=http://zipkin:9411/api/v2/spans
    depends_on:
      - zipkin

  server-b:
    build:
      context: .
      dockerfile: Dockerfile
    image: opentelemetry-server-b:latest
    ports:
      - "8081:8081"
    environment:
      - SERVICE_NAME=server-b
      - OTEL_EXPORTER_ZIPKIN_ENDPOINT=http://zipkin:9411/api/v2/spans
    depends_on:
      - zipkin

  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"

networks:
  default:
    name: opentelemetry-network
